M48
; DRILL file {KiCad 9.0.2} date 2025-07-06T13:36:03-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-06T13:36:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X50.5Y-46.91
X50.5Y-62.0
X50.5Y-77.09
X60.66Y-46.91
X60.66Y-62.0
X60.66Y-77.09
T2
X55.58Y-46.91
X55.58Y-62.0
X55.58Y-77.09
M30
